print("      *")
print("    *","*",sep=" "*4)
print("   *","*",sep=" "*6)
print("  *", "*", sep=" "*8)
print(" *","*", sep=" "*10)
print("***","***",sep=" "*8)
print("  *","   "*2,"*", end="\n"*2)
print("  *","   "*2,"*", end="\n"*2)
print(" ","*****"*2)
